### Test post vendedor
POST http://localhost:3000/managers
Content-Type: application/json

{
    "nombre1": "carlos",
    "nombre2": "diego",
    "apellido1": "mendizabal",
    "apellido2": "mostajo",
    "fechaNacimiento":"1999-12-12",
    "password":"0000",
    "repassword":"0000",
    "ci":"6105591",
    "mail":"carlos.mendizabal@ucb.edu.bo",
    "ciudad":"la paz",
    "cuenta":"4343432234"
}

### Test post comprador
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nombre1": "carlos",
    "nombre2": "diego",
    "apellido1": "mendizabal",
    "apellido2": "mostajo",
    "fechaNacimiento":"1999-12-12",
    "password":"0000",
    "repassword":"0000",
    "ci":"6105591",
    "mail":"carlos.mendizabal@ucb.edu.bo"
}

### Test post vendedor
POST http://localhost:3000/vendedores
Content-Type: application/json

{
    "nombre1": "carlos",
    "nombre2": "diego",
    "apellido1": "mendizabal",
    "apellido2": "mostajo",
    "fechaNacimiento":"1999-12-12",
    "password":"0000",
    "repassword":"0000",
    "ci":"6105591",
    "mail":"carlos.mendizabal@ucb.edu.bo",
    "pais":"Bolivia",
    "ciudad":"La Paz",
    "telefono":"748299291",
    "cuenta":"21311541231"
}

### Test get datos de clientes
GET http://localhost:3000/clientes
Content-Type: application/json

### Test get datos de vendedores
GET http://localhost:3000/vendedores
Content-Type: application/json

### Test post evento
POST http://localhost:3000/events
Content-Type: application/json

{
    "nombre": "conciertofin",
    "lugar":"estadio hernando siles",
    "capacidad":1000,
    "estado":"pendiente",
    "organizador":"empresa1",
    "fechaInicio":"2020-12-12",
    "fechaFin":"2020-12-29",
    "precio":0.01
}

### Test put estado de evento
PUT http://localhost:3000/events
Content-Type: application/json

{
    "_id": "624b103f9b8bbe3d3994ddfc",
    "estado":"pendiente"
}

### Test get eventos
GET http://localhost:3000/events
Content-Type: application/json

### Test get eventos por nombre
GET http://localhost:3000/events?nombre=conciertofin
Content-Type: application/json

### Test get datos de managers
GET http://localhost:3000/managers
Content-Type: application/json

### Test get datos de manager de evento
GET http://localhost:3000/managers?_id="a"
Content-Type: application/json

### Test put imagenes de evento
PUT http://localhost:3000/events
Content-Type: application/json

{
    "_id": "62473dd8186af518eb739b23",
    "images":[]
}



//plantillas calls
### Test Get
GET http://localhost:3000/
Content-Type: application/json

### Test Post
POST http://localhost:3000/
Content-Type: application/json

{
    "id": "user"
}

### Test Put
PUT http://localhost:3000/user
Content-Type: application/json

{
    "user": "user"
}

### Test Delete
DELETE  http://localhost:3000/user
Content-Type: application/json

{
    "id": "user"
}