### Test post evento
POST http://localhost:3000/eventos
Content-Type: application/json

{
    "nombre": "concierto a",
    "lugar":"estadio hernando siles",
    "capacidad":1000,
    "organizador":"625f33b12232710a2b941908",
    "fechaInicio":"2022-05-19",
    "fechaFin":"2022-05-19",
    "precio":0.01
}

### Test post cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nombre1": "abc",
    "nombre2": "def",
    "apellido1": "gasd",
    "apellido2": "dsad",
    "fechaNacimiento":"1980-03-05",
    "password":"0000",
    "repassword":"0000",
    "ci":"613215",
    "mail":"illanesm965@gmail.com",
    "telefono":75822287,
    "departamento":"la paz",
    "ciudad":"el alto",
    "smsActivado": true
}

### Test post vendedor (persona)
POST http://localhost:3000/vendedores
Content-Type: application/json

{
    "nombre1": "carlos",
    "nombre2": "diego",
    "apellido1": "mendizabal",
    "apellido2": "mostajo",
    "fechaNacimiento":"2022-04-04",
    "password":"0000a",
    "repassword":"0000a",
    "ci":"6105591",
    "mail":"illanesm965@gmail.com",
    "telefono":75822287,
    "departamento":"la paz",
    "ciudad":"el alto",
    "banco":"bcp",
    "cuenta":"3341-2312",
    "esEmpresa":false
}

### Test post vendedor (empresa)
POST http://localhost:3000/vendedores
Content-Type: application/json

{
    "nombre1": "carlos",
    "nombre2": "diego",
    "apellido1": "mendizabal",
    "apellido2": "mostajo",
    "fechaNacimiento":"2022-04-04",
    "password":"0000a",
    "repassword":"0000a",
    "ci":"6105591",
    "mail":"illanesm965@gmail.com",
    "telefono":59175822287,
    "departamento":"la paz",
    "ciudad":"el alto",
    "banco":"bcp",
    "cuenta":"3341-2312",
    "esEmpresa":true,
    "nombreEmpresa": "Coca Cola",
    "telefonoEmpresa": 273829,
    "direccionEmpresa": "camino a viacha",
    "sitioWebEmpresa": "www.cocacola.com"
}

### Test put estado de evento
PUT http://localhost:3000/eventos
Content-Type: application/json

{
    "_id": "624c85c2c029328daeaa69a7",
    "estado":"cancelado"
}

### Test put estado y capacidad de evento
PUT http://localhost:3000/eventos
Content-Type: application/json

{
    "_id": "624c85c2c029328daeaa69a7",
    "estado":"pendiente",
    "capacidad":200
}

### Test put capacidad de evento
PUT http://localhost:3000/eventos
Content-Type: application/json

{
    "_id": "625f218fba027d0fe73f05cb",
    "capacidad":500
}

### Test get eventos de un vendedor
GET http://localhost:3000/eventos?organizador=empresa1
Content-Type: application/json

### Test get eventos por nombre
GET http://localhost:3000/eventos?nombre=eventoc
Content-Type: application/json

### Test get datos de vendedores
GET http://localhost:3000/vendedores
Content-Type: application/json

### Test get datos de un cliente
GET http://localhost:3000/clientes?_id=6260638c4537ab80f2a1955a
Content-Type: application/json

### Test get datos de un vendedor
GET http://localhost:3000/vendedores?_id=624f2c35c9724fd7af080005
Content-Type: application/json

### Test get datos de un vendedor
GET http://localhost:3000/vendedores?mail=vilcs99@gmail.com
Content-Type: application/json

### Test post compra
POST http://localhost:3000/compras
Content-Type: application/json

{
  "idEvento": "c",
  "nombreEvento": "conciertf",
  "direccionEvento": "centro prado calle 233",
  "fechaInicio": "2022-06-06",
  "fechaFin": "2022-06-06",
  "idCliente": "6254efe0e70d04c8bac51cd5",
  "nombre1": "carlos",
  "nombre2": "diego",
  "apellido1": "mendizabal",
  "apellido2": "mostajo",
  "nit": 324243,
  "cantidadTickets": 3,
  "precioUnitario": 350,
  "correoCliente": "carlosmendizabaltickets@gmail.com",
  "telefono": 73747260,
  "smsActivado": true
}

### Test cancelar compras desde vendedor
PUT http://localhost:3000/cancelacionvendedor
Content-Type: application/json

{
    "idEvento": "kkfeosy"
}

### Test get compras
GET http://localhost:3000/compras
Content-Type: application/json

### Test get confirmar correo de un cliente
GET http://localhost:3000/confirmacionclientes?c=625ee9abb73aa343fa674a07
Content-Type: application/json

### Test get confirmar correo de un vendedor
GET http://localhost:3000/confirmacionvendedores?v=625ee9abb73aa343fa674a07
Content-Type: application/json

### Test get compras de un cliente
GET http://localhost:3000/compras?_id=ynnyrlgh
Content-Type: application/json

### Test put smsActivado de cliente
PUT http://localhost:3000/clientes
Content-Type: application/json

{
    "_id": "6254efe0e70d04c8bac51cd5",
    "smsActivado":true
}

### Test auth de un cliente
GET http://localhost:3000/authclientes?mail=illanesm965@gmail.com&password=0000a
Content-Type: application/json

### Test auth de un vendedor
GET http://localhost:3000/authvendedores?mail=illanesm965@gmail.com&password=0000a
Content-Type: application/json

### Test put (aumentar tickets vendidos)
PUT http://localhost:3000/tickets
Content-Type: application/json

{
    "_id": "625f218fba027d0fe73f05cb",
    "tickets":500
}

### Test get (verificar si se puede cambiar capacidad)
GET http://localhost:3000/verificacioncapacidad
Content-Type: application/json

{
    "_id": "625f218fba027d0fe73f05cb",
    "capacidad": 1000
}

### Test get datos de clientes
GET http://localhost:3000/clientes
Content-Type: application/json

### Test get eventos
GET http://localhost:3000/eventos
Content-Type: application/json

### Test put habilitar tickets antes de cancelar compra
PUT http://localhost:3000/eventos
Content-Type: application/json

{
    "_id": "62604fb9e455ffa44de3b392",
    "ticketsVendidos": 8
}

### Test put cancelarCompra
PUT http://localhost:3000/compras
Content-Type: application/json

{
    "_id": "6260589d31c7f5c3eadb7a4e"
}

### Test put modificar password comprador
PUT http://localhost:3000/clientes
Content-Type: application/json

{
    "_id": "62605222e455ffa44de3b39e",
    "oldPassword": "0000",
    "newPassword": "aaaa"
}

### Test put modificar telefono comprador
PUT http://localhost:3000/clientes
Content-Type: application/json

{
    "_id": "62605222e455ffa44de3b39e",
    "telefono": 3123123
}

### Test put modificar password, telefono y smsActivado comprador
PUT http://localhost:3000/clientes
Content-Type: application/json

{
    "_id": "62605222e455ffa44de3b39e",
    "oldPassword": "aaaa",
    "newPassword": "bbb",
    "telefono": 42394933,
    "smsActivado": false
}



//plantillas calls

### Test Delete
DELETE  http://localhost:3000/user
Content-Type: application/json

{
    "id": "user"
}